In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_parquet('Clean_flight_Data.parquet')

In [3]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'CRS_ARR_TIME', 'ARR_DELAY', 'CANCELLED',
       'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'DISTANCE', 'YEAR',
       'MONTH_NUM', 'MONTH_NAME', 'DAY_NUM', 'DAY_NAME', 'IS_WEEKEND', 'ROUTE',
       'IS_DELAY', 'DEP_HOUR'],
      dtype='object')

In [4]:
print(df['CANCELLED'].value_counts())

print(df['DIVERTED'].value_counts())

CANCELLED
0.0    2913804
Name: count, dtype: int64
DIVERTED
0.0    2913804
Name: count, dtype: int64

In [5]:
df = df.drop(columns=[
    'CANCELLED',
    'CANCELLATION_CODE',
    'DIVERTED',
    'IS_DELAY'
], errors='ignore')

In [6]:
df[['AIRLINE','AIRLINE_DOT','AIRLINE_CODE','DOT_CODE']].drop_duplicates().head(30)

,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE
0,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977
1,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790
4,Spirit Air Lines,Spirit Air Lines: NK,NK,20416
5,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393
6,American Airlines Inc.,American Airlines Inc.: AA,AA,19805
7,Republic Airline,Republic Airline: YX,YX,20452
9,Alaska Airlines Inc.,Alaska Airlines Inc.: AS,AS,19930
19,JetBlue Airways,JetBlue Airways: B6,B6,20409
23,PSA Airlines Inc.,PSA Airlines Inc.: OH,OH,20397
25,Allegiant Air,Allegiant Air: G4,G4,20368
26,ExpressJet Airlines LLC d/b/a aha!,ExpressJet Airlines LLC d/b/a aha!: EV,EV,20366
33,SkyWest Airlines Inc.,SkyWest Airlines Inc.: OO,OO,20304
41,Endeavor Air Inc.,Endeavor Air Inc.: 9E,9E,20363
52,Envoy Air,Envoy Air: MQ,MQ,20398
61,Frontier Airlines Inc.,Frontier Airlines Inc.: F9,F9,20436
65,Mesa Airlines Inc.,Mesa Airlines Inc.: YV,YV,20378
126,Horizon Air,Horizon Air: QX,QX,19687
222,Hawaiian Airlines Inc.,Hawaiian Airlines Inc.: HA,HA,19690

In [7]:
df = df.drop(columns=[
    'AIRLINE',
    'AIRLINE_DOT',
    'DOT_CODE'
])

In [8]:
print(df[['ORIGIN','ORIGIN_CITY']].head(10))

print(df[['DEST','DEST_CITY']].head(10))

  ORIGIN          ORIGIN_CITY
0    FLL  Fort Lauderdale, FL
1    MSP      Minneapolis, MN
2    DEN           Denver, CO
3    MSP      Minneapolis, MN
4    MCO          Orlando, FL
5    DAL           Dallas, TX
6    DCA       Washington, DC
7    HSV       Huntsville, AL
8    IAH          Houston, TX
9    SEA          Seattle, WA
  DEST              DEST_CITY
0  EWR             Newark, NJ
1  SEA            Seattle, WA
2  MSP        Minneapolis, MN
3  SFO      San Francisco, CA
4  DFW  Dallas/Fort Worth, TX
5  OKC      Oklahoma City, OK
6  BOS             Boston, MA
7  DCA         Washington, DC
8  LAX        Los Angeles, CA
9  FAI          Fairbanks, AK

In [9]:
df = df.drop(columns=[
    'ORIGIN_CITY',
    'DEST_CITY'
])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2913804 entries, 0 to 2913803
Data columns (total 18 columns):
 #   Column            Dtype
---  ------            -----
 0   FL_DATE           datetime64[ns]
 1   AIRLINE_CODE      object
 2   FL_NUMBER         int64
 3   ORIGIN            object
 4   DEST              object
 5   CRS_DEP_TIME      int64
 6   CRS_ARR_TIME      int64
 7   ARR_DELAY         float64
 8   CRS_ELAPSED_TIME  float64
 9   DISTANCE          float64
 10  YEAR              int32
 11  MONTH_NUM         int32
 12  MONTH_NAME        object
 13  DAY_NUM           int32
 14  DAY_NAME          object
 15  IS_WEEKEND        int64
 16  ROUTE             object
 17  DEP_HOUR          int64
dtypes: datetime64[ns](1), float64(3), int32(3), int64(5), object(6)
memory usage: 366.8+ MB

In [11]:
df = df.drop(columns=[
    'MONTH_NAME',
    'DAY_NAME'
])

In [12]:
print(df['YEAR'].value_counts().sort_index())

YEAR
2019    742096
2020    449823
2021    599709
2022    667762
2023    454414
Name: count, dtype: int64

In [13]:
print(df['ROUTE'].nunique())

print(df['AIRLINE_CODE'].nunique())

print(df['ORIGIN'].nunique())

print(df['DEST'].nunique())

7765
18
380
380

In [14]:
df['MONTH_NUM']=df['MONTH_NUM'].astype('object')
df['DAY_NUM']=df['DAY_NUM'].astype('object')
df['YEAR']=df['YEAR'].astype('object')

In [15]:
print(df['ROUTE'].value_counts().describe())

count    7765.000000
mean      375.248422
std       534.202443
min         1.000000
25%        36.000000
50%       165.000000
75%       501.000000
max      5218.000000
Name: count, dtype: float64

In [16]:
df = df[df['ARR_DELAY'] <= 180].copy()

In [17]:
print(df['ROUTE'].nunique())
print(df.groupby('ROUTE').size().describe())

7761
count    7761.000000
mean      371.284757
std       528.573566
min         1.000000
25%        36.000000
50%       164.000000
75%       497.000000
max      5170.000000
dtype: float64

In [18]:
print(df['ARR_DELAY'].describe())

count    2.881541e+06
mean     6.088104e-01
std      2.955697e+01
min     -9.600000e+01
25%     -1.600000e+01
50%     -7.000000e+00
75%      6.000000e+00
max      1.800000e+02
Name: ARR_DELAY, dtype: float64

In [19]:
print((df['ARR_DELAY'] > 180).sum())
print((df['ARR_DELAY'] > 300).sum())
print((df['ARR_DELAY'] > 600).sum())

0
0
0

In [20]:
num = [
    
    'CRS_DEP_TIME',
    'CRS_ARR_TIME',
    'CRS_ELAPSED_TIME',
    'DISTANCE',
    'AIRLINE_AVG_DELAY',
    'ORIGIN_AVG_DELAY',
    'DEST_AVG_DELAY',
    'MONTH_AVG_DELAY',
    'DEP_HOUR_AVG_DELAY',
    'ROUTE_FREQ',
    'ORIGIN_FREQ',
    'DEST_FREQ',
    'AIRLINE_FREQ'
]
cat_be = [
    'AIRLINE_CODE',
    'ORIGIN',
    'DEST',
    
    'MONTH_NUM',
    'DAY_NUM',
    'ROUTE',
    'IS_WEEKEND',
    'DEP_HOUR',
    'SEASON',
   
]
x = df.drop(['ARR_DELAY', 'FL_DATE','FL_NUMBER','YEAR'], axis=1)
y = df['ARR_DELAY']
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler

scaler=RobustScaler()

num_pipeline=Pipeline(steps=[('Scaling',scaler)])
from category_encoders import BinaryEncoder
be=BinaryEncoder()
be_pipeline=Pipeline(steps=[('BE',be)])
from sklearn.compose import ColumnTransformer

preprocessing=ColumnTransformer(transformers=[('Num_pipeline',num_pipeline,num),
                                              ('Be',be_pipeline,cat_be)],remainder='passthrough')
from xgboost import XGBRegressor

from sklearn.base import BaseEstimator, TransformerMixin

class HistoricalFeaturesTransformer(BaseEstimator, TransformerMixin):

    def fit(self, X, y):
        temp = X.copy()
        temp['ARR_DELAY'] = y

        self.global_avg_ = y.mean()

        self.airline_avg_ = temp.groupby('AIRLINE_CODE')['ARR_DELAY'].mean().to_dict()
        self.origin_avg_ = temp.groupby('ORIGIN')['ARR_DELAY'].mean().to_dict()
        self.dest_avg_ = temp.groupby('DEST')['ARR_DELAY'].mean().to_dict()
        self.month_avg_ = temp.groupby('MONTH_NUM')['ARR_DELAY'].mean().to_dict()
        self.hour_avg_ = temp.groupby('DEP_HOUR')['ARR_DELAY'].mean().to_dict()
        

        self.route_freq_ = temp['ROUTE'].value_counts().to_dict()
        self.origin_freq_ = temp['ORIGIN'].value_counts().to_dict()
        self.dest_freq_ = temp['DEST'].value_counts().to_dict()
        self.airline_freq_ = temp['AIRLINE_CODE'].value_counts().to_dict()
        

        

        return self

    def transform(self, X):
        X = X.copy()

        X['AIRLINE_AVG_DELAY'] = X['AIRLINE_CODE'].map(self.airline_avg_).fillna(self.global_avg_)
        X['ORIGIN_AVG_DELAY'] = X['ORIGIN'].map(self.origin_avg_).fillna(self.global_avg_)
        X['DEST_AVG_DELAY'] = X['DEST'].map(self.dest_avg_).fillna(self.global_avg_)
        X['MONTH_AVG_DELAY'] = X['MONTH_NUM'].map(self.month_avg_).fillna(self.global_avg_)
        X['DEP_HOUR_AVG_DELAY'] = X['DEP_HOUR'].map(self.hour_avg_).fillna(self.global_avg_)
        

        X['ROUTE_FREQ'] = X['ROUTE'].map(self.route_freq_).fillna(0)
        X['ORIGIN_FREQ'] = X['ORIGIN'].map(self.origin_freq_).fillna(0)
        X['DEST_FREQ'] = X['DEST'].map(self.dest_freq_).fillna(0)
        X['AIRLINE_FREQ'] = X['AIRLINE_CODE'].map(self.airline_freq_).fillna(0)
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Winter'
            elif month in [3, 4, 5]:
                return 'Spring'
            elif month in [6, 7, 8]:
                return 'Summer'
            else:
                return 'Fall'

        X['SEASON'] = X['MONTH_NUM'].apply(get_season)
        
       

        return X
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline

model_pipeline = Pipeline(
    steps=[
        ('historical_features', HistoricalFeaturesTransformer()),
        ('Preprocessing', preprocessing),
        ('Model', XGBRegressor(
                            random_state=42,
                            n_estimators=300,
                            max_depth=6,
                            learning_rate=0.05,
                            subsample=0.8,
                            colsample_bytree=0.8
                        ))
    ]
)
from sklearn.model_selection import cross_validate

result = cross_validate(
    model_pipeline,
    x,
    y,
    cv=2,
    scoring='r2',
    return_train_score=True,
    n_jobs=-1
)

print('Train Score:', result['train_score'].mean())
print('Test Score:', result['test_score'].mean())

Train Score: 0.06692719457728336
Test Score: 0.05874604699036873

In [21]:
train_df = df[df['YEAR'] < 2023]
test_df  = df[df['YEAR'] == 2023]

X_train = train_df.drop(['ARR_DELAY', 'FL_DATE'], axis=1)
y_train = train_df['ARR_DELAY']

X_test = test_df.drop(['ARR_DELAY', 'FL_DATE'], axis=1)
y_test = test_df['ARR_DELAY']

model_pipeline.fit(X_train, y_train)

y_pred_train = model_pipeline.predict(X_train)
y_pred_test = model_pipeline.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error

print("Train R2:", r2_score(y_train, y_pred_train))
print("Test R2:", r2_score(y_test, y_pred_test))

print("Train MAE:", mean_absolute_error(y_train, y_pred_train))
print("Test MAE:", mean_absolute_error(y_test, y_pred_test))

e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)

Train R2: 0.09024492400664308
Test R2: 0.06764971229561478
Train MAE: 17.653899296083424
Test MAE: 20.492635932124067

In [22]:
model_pipeline.fit(x, y)

e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)

Pipeline(steps=[('historical_features', HistoricalFeaturesTransformer()),
                ('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num_pipeline',
                                                  Pipeline(steps=[('Scaling',
                                                                   RobustScaler())]),
                                                  ['CRS_DEP_TIME',
                                                   'CRS_ARR_TIME',
                                                   'CRS_ELAPSED_TIME',
                                                   'DISTANCE',
                                                   'AIRLINE_AVG_DELAY',
                                                   'ORIGIN_AVG_DELAY',
                                                   'DEST_AVG_DELAY',
                                                   'MONTH_AVG_DELAY',
                                                   'DEP_HOUR...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=6, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, random_state=42, ...))])

In [23]:
import joblib

joblib.dump(model_pipeline, "flight_delay_model.pkl")

['flight_delay_model.pkl']

In [24]:
loaded_model = joblib.load("flight_delay_model.pkl")

loaded_model.predict(x.tail(1))

e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)
e:\CDSP\Projects\ML Projects\Final Project\flight_env\Lib\site-packages\category_encoders\ordinal.py:198: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[column] = X[column].astype("object").fillna(np.nan).map(col_mapping)

array([-4.204657], dtype=float32)

In [25]:
x.tail(1)

,AIRLINE_CODE,ORIGIN,DEST,CRS_DEP_TIME,CRS_ARR_TIME,CRS_ELAPSED_TIME,DISTANCE,MONTH_NUM,DAY_NUM,IS_WEEKEND,ROUTE,DEP_HOUR
2913803,WN,LGB,SJC,730,840,70.0,324.0,6,5,1,LGB → SJC,7

In [26]:
df.tail(1)

,FL_DATE,AIRLINE_CODE,FL_NUMBER,ORIGIN,DEST,CRS_DEP_TIME,CRS_ARR_TIME,ARR_DELAY,CRS_ELAPSED_TIME,DISTANCE,YEAR,MONTH_NUM,DAY_NUM,IS_WEEKEND,ROUTE,DEP_HOUR
2913803,2019-06-15,WN,2823,LGB,SJC,730,840,-10.0,70.0,324.0,2019,6,5,1,LGB → SJC,7

In [27]:
route_distance = (
    df.groupby(['ORIGIN', 'DEST'])['DISTANCE']
      .first()
      .reset_index()
)

In [28]:
route_distance.to_csv('route_distance.csv', index=False)

In [29]:
x.columns.tolist()

['AIRLINE_CODE',
 'ORIGIN',
 'DEST',
 'CRS_DEP_TIME',
 'CRS_ARR_TIME',
 'CRS_ELAPSED_TIME',
 'DISTANCE',
 'MONTH_NUM',
 'DAY_NUM',
 'IS_WEEKEND',
 'ROUTE',
 'DEP_HOUR']